services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    ports:
      - "8383:80"
    volumes:
      - /home/homeadmin:/srv
      - ./config/filebrowser.db:/database.db
    restart: unless-stopped